# Generated by Django 5.2.18 on 2026-10-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pdf_description",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="post",
            name="pdf_file",
            field=models.FileField(blank=True, upload_to="anexos/noticias/"),
        ),
    ]
